In [3]:
import numpy as np
np.__version__

'2.3.5'

In [4]:
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [5]:
a = np.array([10,20,30,40])
a[0]
a[1:3]

array([20, 30])

In [6]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
a + b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [11]:
arr = np.array([7, 4, 1, 12, 9, 0])
for x in arr:
    if x > 5:
        print(x)

7
12
9


In [12]:
arr = np.array([7, 4, 1, 12, 9, 0])
for x in arr:
    if x % 2 == 0:
        print(x)

4
12
0


In [14]:
arr = np.array([7, 4, 1, 12, 9, 0])

# Use np.where to replace odd numbers with -1
arr = np.where(arr % 2 == 1, -1, arr)

print(arr)

[-1  4 -1 12 -1  0]


In [15]:
arr = np.array([7, 4, 1, 12, 9, 0])

reshaped_arr_2_3 = arr.reshape(2, 3)
print(f"Reshaped to (2, 3):\n{reshaped_arr_2_3}")

reshaped_arr_3_2 = arr.reshape(3, 2)
print(f"\nReshaped to (3, 2):\n{reshaped_arr_3_2}")

# Flattening the array returns a 1D array
flattened_arr = arr.flatten()
print(f"\nFlattened array: {flattened_arr}")

Reshaped to (2, 3):
[[ 7  4  1]
 [12  9  0]]

Reshaped to (3, 2):
[[ 7  4]
 [ 1 12]
 [ 9  0]]

Flattened array: [ 7  4  1 12  9  0]


In [17]:
arr = np.linspace(0,10)
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [18]:
arr = np.linspace(0,10, num=5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
arr = np.linspace(0,10, num=300)
print(arr)

[ 0.          0.03344482  0.06688963  0.10033445  0.13377926  0.16722408
  0.2006689   0.23411371  0.26755853  0.30100334  0.33444816  0.36789298
  0.40133779  0.43478261  0.46822742  0.50167224  0.53511706  0.56856187
  0.60200669  0.63545151  0.66889632  0.70234114  0.73578595  0.76923077
  0.80267559  0.8361204   0.86956522  0.90301003  0.93645485  0.96989967
  1.00334448  1.0367893   1.07023411  1.10367893  1.13712375  1.17056856
  1.20401338  1.23745819  1.27090301  1.30434783  1.33779264  1.37123746
  1.40468227  1.43812709  1.47157191  1.50501672  1.53846154  1.57190635
  1.60535117  1.63879599  1.6722408   1.70568562  1.73913043  1.77257525
  1.80602007  1.83946488  1.8729097   1.90635452  1.93979933  1.97324415
  2.00668896  2.04013378  2.0735786   2.10702341  2.14046823  2.17391304
  2.20735786  2.24080268  2.27424749  2.30769231  2.34113712  2.37458194
  2.40802676  2.44147157  2.47491639  2.5083612   2.54180602  2.57525084
  2.60869565  2.64214047  2.67558528  2.7090301   2

In [2]:
import numpy as np
x = np.array([2, 4, 5, 7, 9])
x[2]

5